Repository mesh-adaptation/docs, pull requests merged in 2024-11, with the labels that each got.

#61 Update how docker workflows are triggered
  .github/workflows/docker_firedrake-parmmg.yml
  .github/workflows/docker_petsc-parmmg.yml
Labels: enhancement

#63 Link burgers goal-oriented demo to docs
  docs/source/goalie/index.rst
Labels: documentation

#67 Allow switching Docker image in reusable test workflow
  .github/workflows/reusable_test_suite.yml
Labels: testing, install

#59 UM2N Docker build
  .dockerignore
  .github/workflows/docker_firedrake-parmmg.yml
  .github/workflows/docker_firedrake-um2n.yml
  .github/workflows/docker_petsc-parmmg.yml
  docker/Dockerfile.firedrake-parmmg
  docker/Dockerfile.firedrake-um2n
  docker/Dockerfile.petsc-parmmg
  docker/Makefile
Labels: testing, install
