Repository mesh-adaptation/docs, pull requests merged in 2024-09, with the labels that each got.

#40 Add PETSc Docker build
  .github/workflows/docker_firedrake.yml
  .github/workflows/docker_petsc.yml
  docker/Dockerfile.firedrake
  docker/Dockerfile.petsc
  docker/Makefile
  install/petsc_reconfigure_options.txt
Labels: bug, install, PRIORITY

#46 #45: Add reusable workflows
  .github/workflows/reusable_citation_check.yml
  .github/workflows/reusable_test_suite.yml
Labels: testing

#47 Reusable Docker workflows
  .github/workflows/docker_firedrake-parmmg.yml
  .github/workflows/docker_firedrake.yml
  .github/workflows/docker_petsc-parmmg.yml
  .github/workflows/docker_petsc.yml
  .github/workflows/reusable_docker_build.yml
Labels: install

#48 Add Animate bubble shear demo
  docs/source/animate/index.rst
Labels: documentation
