Repository mesh-adaptation/docs, pull requests merged in 2024-12, with the labels that each got.

#52 Workflow to build and deploy docs
  .github/workflows/build_docs.yml
  docs/source/UM2N/index.rst
Labels: documentation, PRIORITY

#81 Build docs if other repos were changed in the last 24h
  .github/workflows/build_docs.yml
Labels: documentation

#83 Fix for demos failing in automated docs build
  .github/workflows/build_docs.yml
Labels: bug, documentation, PRIORITY

#87 Unify PETSc and Firedrake docker images
  .github/workflows/docker_firedrake-parmmg.yml
  .github/workflows/docker_petsc-parmmg.yml
  docker/Dockerfile.firedrake-parmmg
  docker/Dockerfile.petsc-parmmg
Labels: optimisation

#77 Add workflow to test Firedrake installation
  .github/workflows/test_firedrake_install.yml
Labels: testing

#68 Install MPI by default; always check_env; consistent tab formatting
  .github/workflows/test_firedrake_install.yml
  install/Makefile
Labels: install

#88 In UM2N Dockerfile use firedrake-parmmg as base
  .github/workflows/docker_firedrake-um2n.yml
  docker/Dockerfile.firedrake-um2n
Labels: optimisation

#89 Use UM2N container in build_docs.yml
  .github/workflows/build_docs.yml
Labels: optimisation

#90 Simplify reusable test workflow
  .github/workflows/reusable_test_suite.yml
Labels: testing, clarity

#92 Skip demos in docs build that do not produce figures
  docs/Makefile
Labels: optimisation

#94 Fix MPI setup in Docker build
  docker/Dockerfile.firedrake-parmmg
Labels: bug, install
