Repository mesh-adaptation/docs, pull requests merged in 2025-01, with the labels that each got.

#98 Add install step in test workflow
  .github/workflows/reusable_test_suite.yml
Labels: testing, install

#99 Fix failing test for firedrake install
  .github/workflows/test_firedrake_install.yml
Labels: bug, testing

#95 Install optional dev dependencies
  .github/workflows/test_firedrake_install.yml
  docker/Dockerfile.firedrake-parmmg
  docker/Dockerfile.firedrake-um2n
Labels: install

#96 Add doubly periodic MA demo
  docs/source/movement/index.rst
Labels: documentation

#102 Add wiki to repo
  .github/workflows/publish_wiki.yml
  wiki/Citing.md
  wiki/Development-Practices.md
  wiki/Home.md
  wiki/Installation-Instructions.md
  wiki/Maintainer-Notes.md
  wiki/Running-on-HPC.md
Labels: documentation, enhancement

#110 Document all members
  docs/source/conf.py
Labels: documentation

#111 Mention Slack channels on the website
  docs/source/index.rst
Labels: documentation, docsprint
