Repository mesh-adaptation/docs, pull requests merged in 2025-03, with the labels that each got.

#114 Updates to `firedrake-parmmg` and testing due to Firedrake's new `pip install`
  .github/workflows/reusable_test_suite.yml
  docker/Dockerfile.firedrake-parmmg
Labels: install, PRIORITY

#119 Avoid workflow vulnerabilities
  .github/workflows/publish_wiki.yml
  .github/workflows/reusable_test_suite.yml
Labels: testing

#117 Add linting workflow including zizmor
  .github/workflows/build_docs.yml
  .github/workflows/docker_firedrake-um2n.yml
  .github/workflows/linting.yml
  .github/workflows/publish_wiki.yml
  .github/workflows/reusable_citation_check.yml
  .github/workflows/reusable_docker_build.yml
  .github/workflows/reusable_test_suite.yml
Labels: testing

#118 Run parallel tests with 3 processes in the CI
  .github/workflows/reusable_test_suite.yml
Labels: testing

#115 Update `Dockerfile.firedrake-um2n`
  docker/Dockerfile.firedrake-um2n
Labels: install
